name: Build Template
on:
  workflow_dispatch:
  
jobs:
  build:
    
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
        
    - uses: actions/checkout@v4
      with:
        repository: gmij/dw.gmij.win
        sparse-checkout: |
          .
          .github/workflows/
        path: template
    - uses: actions/checkout@v4
      with:
        repository: gmij/dw.template
        path: remote
        token: ${{ secrets.PAT }}
          
    - name: remove git & copy data
      run: |
        cd template
        rm -rf .git
        cp -rf . ../remote

    - name: Commit Changes
      run: |
        cd remote
        ls
        
        git config --local user.email "gmij@qq.com"
        git config --local user.name "Gmij with Github Actions"
        git add .
        git diff-index --quiet HEAD || git commit -m "Image Detail"
        git push -f
